smash-transport/smash-analysis

python_scripts/version.py
* Git describe only works once there was a first tag.
* In case the analysis suite is downloaded and not cloned, the history
is not loaded, meaning tags are not loaded either.
* Therefore, 'git describes' which is used to determine the SMASHana
version, fails
* Fixed the crash by catching an exception and alternatively returning
an unknown version.
Fixes #15
=> Circumvent crash if 'git describe' fails

test/dileptons/AgAg/config.yaml
Should be the default, which is `quadratic`.
=> Fix impact parameter sampling for dileptons in AgAg

test/energy_scan/mult_and_spectra_plotter.py
This is a fix for #34 .
I included another check if the file of experimental data follows the name convention of the files generated from STAR data.
I attach some plots which show that the experimental data is now plotted correctly.
[mtspectra_AuAuPbPb_SPS_2212.pdf](https://github.com/smash-transport/smash-analysis/files/6419796/mtspectra_AuAuPbPb_SPS_2212.pdf)
[mtspectra_AuAuPbPb_RHIC_LHC_211.pdf](https://github.com/smash-transport/smash-analysis/files/6419799/mtspectra_AuAuPbPb_RHIC_LHC_211.pdf)
[mtspectra_AuAuPbPb_RHIC_LHC_321.pdf](https://github.com/smash-transport/smash-analysis/files/6419800/mtspectra_AuAuPbPb_RHIC_LHC_321.pdf)
=> Extend the particle name extraction for the STAR data files.

test/elastic_box/CMakeLists.txt
This fixes crashes of the elastic box test for low volumes 
(elastic_box_scatrate_vs_V_sims target) and makes the different criteria 
runs more consistent.
The matching is not exact, but only roughly the chosen to be the same.
=> Reduce grid cell length for stochastic to match geometric criterion

test/angular_distributions/plot_t.py, test/angular_distributions/plot_theta.py
The first two lines of the files were skipped for plotting, although only the first line contains explanations. The data was nevertheless saved and correctly plotted for comparison
[t.pdf](https://github.com/smash-transport/smash-analysis/files/7710804/t.pdf)
[theta.pdf](https://github.com/smash-transport/smash-analysis/files/7710805/theta.pdf)
.
=> Fix plotting bug

test/dileptons/decaymodes.txt, test/dileptons/definitions.py, test/dileptons/plot_hist.py
Extend recognized dilepton sources with (in SMASH-2.1) newly available 
direct N(1520) dilepton Dalitz decay. Not enabled by default. 
In addition, only plot sources that have contributions.
=> Add dilepton analysis of direct N(1520) Dalitz dilepton decay

python_scripts/comp_to_prev_version.py
A small bug prevented the comparison to previous versions for the covariant criterium in the elastic box. This fixes the problem
[scatrate.pdf](https://github.com/smash-transport/smash-analysis/files/7755036/scatrate.pdf)
.
=> Fix plotting of previous version results for elastic box

python_scripts/comp_to_prev_version.py
A recent fix introduced a bug in the coloring of elastic box plots. This fixes the bug.
=> Fix color in comparison to previous version

python_scripts/read_binary_output.py
It often happens that SMASH produces unfinished runs, for example because
the time ended on the cluster, or SMASH crashed for some reason. Often
information from these unfinished runs is very useful, so it makes sense
for the read-out script to consume all the useful information and stop
at the right moment without crash.
This little modification allows the read-in script to read input file
until the first broken block without crashing.
Signed-off-by: Dmytro Oliinychenko <doliinychenko@lbl.gov>
=> Avoid crashes when reading unfinished files

test/detailed_balance/plotting/plot_reactions_number.py
Besides being a bugfix, this is useful because I like to use this code
standalone, outside of analysis suite -- in this setup comparison to previous
versions is off. And I need it to be really off and not crash when previous
version data is not present.
Signed-off-by: Dmytro Oliinychenko <doliinychenko@lbl.gov>
=> Fix plotting script option to compare to previous versions

test/angular_distributions/plot_t.py, test/angular_distributions/plot_theta.py
Hopefully, this should fix the problem in the _angular_distributions_ test plots about the missing curves of the previous SMASH version that refer to a Delta baryon. I tested it with a very small number of events and it seems to work as expected, however I strongly recommend not only to examine the simple changes in the code, but also to test it by redrawing the plots of the recent analysis.
=> Fix missing Delta reaction curves of previous SMASH version in angular distributions comparison plots

cmake/FloatMath.cmake, test/cross_sections/loewe_analysis/main_cross_section_script.bash
This PR upgrades two `python2` invocations to `python3`.
Hopefully now none should be left.
This might solve also Issue #53 .
I propose @nilssass as the reviewer, but I also mention @AxelKrypton for a more expert overview (even if actually the modifications are trivial).
=> Left over python2 invocations updated to python3

test/FOPI_pions/CMakeLists.txt
After change to python3, the directory names in `/smash-analysis/build/test/FOPI_pions` get too many decimal points:
```
-- Configuring FOPI_pions/0.4.
-- Configuring FOPI_pions/0.5.
-- Configuring FOPI_pions/0.6000000000000001.
-- Configuring FOPI_pions/0.7000000000000001.
-- Configuring FOPI_pions/0.8.
-- Configuring FOPI_pions/0.9.
-- Configuring FOPI_pions/1.0.
-- Configuring FOPI_pions/1.1.
-- Configuring FOPI_pions/1.2000000000000002.
```
This PR adds a 'round' command in `/smash-analysis/test/FOPI_pions/CMakeLists.txt` to round the energy to one decimal place.
=> Change to python3 changes directory names in FOPI_pions tests

test/energy_scan/mult_and_spectra_plotter.py
The latest test run of the analysis suite showed problems when plotting the spectra for afterburner and energy scan. This PR adresses this issue which arose due deviations in the energies of the experimental data.
=> Fix spectra plotting issues 

python_scripts/comp_to_prev_version.py
This is the fix for #55 . Only a factor in the comparison to old results was missing.
This PR only modifies the display of old results, therefore here a comparison to 
[before ](https://github.com/smash-transport/smash-analysis/files/8520560/ptspectra_AuAuPbPb_RHIC_LHC_211.pdf) and [after](https://github.com/smash-transport/smash-analysis/files/8520569/ptspectra_AuAuPbPb_RHIC_LHC_211.pdf) the changes with dummy simulation data.
=> Fix pT spectra old result scaling

test/report/generate_html.py
Issue #7 noted that it is not intuitively clear how to use generate_html.py .  The current help indeed does not specify the folder structure. I propose this change to point out that this is not intended to be used as a standalone, but in the context of other provided scripts.
=> Propose clearer definition of what folder structure is expected.

CMakeLists.txt, README.md, test/densities/plot_2d_density.py
In order to be executable with latest matplotlib, PR #59 also changed the keyword `nonposy` to `nonpositive`, as otherwise the analysis suite cannot be executed anymore. As a consequence, the minimum version of matplotlib for the analysis suite is now 3.3.1 . Minor changes are needed in order to adapt to the new version.
On a first glance, no changes in the appearance of the plots occured.
=> Upgrade to matplotlib 3.3.1

test/report/store_old_results.sh
Minor fix - afterburner results were not stored in their own folder. Now their own folder is generated.
=> Proper folder structure for old results

test/cross_sections/config.yaml
Changing it breaks the analysis, since `bmax` is set explicitly in `geometrical_cross_section.py`. It would be nice to fix this in the future, perhaps taking the value from the config file.
=> Comment about maximum impact parameter

test/cross_sections/CMakeLists.txt
This flag should be “no” as the $\eta$ is a stable particle (in SMASH). With “yes” this disregarded the contribution from NN(1535), the largest one, for some reason. 
[xs_proton_proton_eta.pdf](https://github.com/smash-transport/smash-analysis/files/10067822/xs_proton_proton_eta.pdf)
=> Set NN->NNeta unstable flag in cross section target to no

python_scripts/ordered_default_dict.py
From `collections` to `collections.abc` module (since python3.3 is lower than version 3.8, which we require)
@AxelKrypton just to be quick :)
=> Update MutableSet module
